name: Typst Derleme
on: [push]

# Node.js 24 kullanımını zorunlu kılıyoruz
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Git Auto Commit için gerekli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Run Typst
        run: typst compile main.typ output.pdf

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Otomatik PDF Güncelleme"
          file_pattern: 'output.pdf'
