name: Typst Derleme
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # En güncel ve resmi topluluk action'ı
      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Run Typst
        run: typst compile main.typ output.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: dokuman
          path: output.pdf
